[Interface]
Address = 10.0.0.1/24
ListenPort = 51820
PrivateKey = qCPE/pVPPvsrjwB9AzUTHCqu6ZkX2oJONcgLkROoCn8=

# Linux peer — add after running 'wg_setup.sh linux'
[Peer]
PublicKey = dKXvxxidKBIbS6ds9dmkqkONVC1XniM5WzbH0kUGiGU=
AllowedIPs = 10.0.0.2/32
